app/urls.py
from django.urls import path
from .views import home, registro, contacto, galeria, agregar_producto, listar_productos, modificar_producto, eliminar_producto,\
agregar_proveedores, listar_proveedores, modificar_proveedores, eliminar_proveedores, agregar_cliente, listar_cliente,\
modificar_cliente, eliminar_cliente, Listar_contacto, modificar_contacto, eliminar_contacto


urlpatterns = [
    path('', home, name='home'),
    path('registro/', registro, name="registro"),
    path('contacto/', contacto, name='contacto'),
    path('listar-contacto/', Listar_contacto, name='listar_contacto'),
    path('modificar-contacto/<id>/', modificar_contacto, name='modificar_contacto'),
    path('eliminar-contacto/<id>/', eliminar_contacto, name='eliminar_contacto'),
    path('galeria/', galeria, name='galeria'),
    path('agregar-producto/', agregar_producto, name='agregar_producto'),
    path('listar-productos/', listar_productos, name='listar_productos'),
    path('modificar-producto/<id>/', modificar_producto, name='modificar_producto'),
    path('eliminar-producto/<id>/', eliminar_producto, name='eliminar_producto'),
    path('agregar-proveedores/', agregar_proveedores, name='agregar_proveedores'),
    path('listar-proveedores/', listar_proveedores, name='listar_proveedores'),
    path('modificar-proveedores/<id>/', modificar_proveedores, name='modificar_proveedores'),
    path('eliminar-proveedores/<id>/', eliminar_proveedores, name='eliminar_proveedores'),
    path('agregar-cliente/', agregar_cliente, name='agregar_cliente'),
    path('listar-cliente/', listar_cliente, name='listar_cliente'),
    path('modificar-cliente/<id>/', modificar_cliente, name='modificar_cliente'),
    path('eliminar-cliente/<id>/', eliminar_cliente, name='eliminar_cliente'),
]

yuyitos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

class Familia(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    codigo_barra = models.IntegerField()
    precio_compra = models.IntegerField()
    precio_venta = models.IntegerField()
    descripcion = models.TextField()
    familia = models.ForeignKey(Familia, on_delete=models.PROTECT)
    fecha_vencimiento = models.DateField()
    stock = models.IntegerField()
    stock_critico = models.IntegerField()

    def __str__(self):
        return self.nombre

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Proveedores(models.Model):
    nombre_completo = models.CharField(max_length=50)
    rut = models.IntegerField()
    direccion = models.CharField(max_length=50)
    comuna = models.CharField(max_length=50)
    telefono = models.IntegerField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)

class Cliente(models.Model):
    nombre_completo = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    telefono = models.IntegerField()

    def __str__(self):
        return self.nombre_completo

opciones_consultas = [
    [0, "Consulta"],
    [1, "Sugerencia"],
    [2, "Reclamo"],
    [3, "Fiado"],
    [4, "Felicitaciones"]
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Almacen Yuyitos</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    {% load static %}

    {% block css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'app/Css/estilos.css' %}">
    
</head>
<body>      
    <h4 class="text-center">Menu Principal Administrador SGI</br>Almacen yuyito</h4>
    <h6 class="text-center">
        <script>
            var meses = new Array ("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");
            var diasSemana = new Array("Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado");
            var f=new Date();
            document.write(diasSemana[f.getDay()] + ", " + f.getDate() + " de " + meses[f.getMonth()] + " de " + f.getFullYear());
        </script>
    </h6>    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/"><img src="{% static 'app/img/logo/YUYITOS.png' %}" alt="logo" class="logo"/></a>      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">                    
                </li>
            </ul>
            <a class="nav-link dropdown-toggle" style="margin-left: auto;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @{{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesion</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'login' %}">iniciar sesión</a>                        
                <a class="dropdown-item" href="{% url 'registro' %}">Registrate</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div id="contenido">

        {% block contenido %}
        {% endblock %}

    </div>

    <footer>
        <div class="marcas">
            <img src="{% static 'app/img/footer/coca-cola.png' %}" height="45px" alt="">
            <img src="{% static 'app/img/footer/ccu.png' %}" height="85px" alt="">
            <img src="{% static 'app/img/footer/soprole.png' %}" height="45px" alt="">
            <img src="{% static 'app/img/footer/luchetti.png' %}" height="45px" alt="">
            <img src="{% static 'app/img/footer/nestle.png' %}" height="45px" alt="">
        </div>
        <div class="logo_footer">
            <img src="{% static 'app/img/footer/YUYITOS1.png' %}" alt="logo">
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="{% static 'app/js/menu.js' %}"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    
    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title": "Felicitaciones",
                    "text": "{{ m }}",
                    "icon": "success"
                })
            </script>
        {% endfor %}
    {% endif %}
    
    {% block js %}
   
    
</body>
</html>
{% endblock %}

app/templates/app/cliente.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}
{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-6 col-md6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Nuevo Cliente</h2>
                <hr>
                <form action="" class="formulario_control" method="post">

                    {% csrf_token %}

                    {{ form | crispy }}
                    <hr>
                    <br>
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                {{ mensaje }}
            </div>
        </div>        
    </div>
</div>

{% endblock %}

app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% block contenido %}
{% load crispy_forms_tags %}
<br><br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2 align='center'>Contactanos!</h2>
                <hr>
                <form action="" class="" method="post">
                    {% csrf_token %}            
                    {{ form | crispy }}
                    <br>
                    <hr>
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="cancelar" class="btn btn-secondary">
                        &nbsp;
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    </div>       
                </form>
                {{mensaje}}
            </div>
        </div>        
    </div>
</div>
<table id="tablacontactos">
    
</table>

{% endblock %}

app/templates/app/galeria.html
{% extends 'app/base.html' %}
{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block contenido %}

<h2>Galería de nuestra tienda</h2>
<br><br>
<div class="galeria">
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda.jpg' %}"><img src="{% static 'app/img/tienda/tienda.jpg' %}"></a>
    <!-- <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda9.jpeg' %}"><img src="{% static 'app/img/tienda/tienda9.jpeg' %}"></a> -->
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda6.jpg' %}"><img src="{% static 'app/img/tienda/tienda6.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda7.jpg' %}"><img src="{% static 'app/img/tienda/tienda7.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda8.jpg' %}"><img src="{% static 'app/img/tienda/tienda8.jpg' %}"></a>     
</div>

{% endblock %}

app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<script>
    $(document).ready(function() {
      $('.slider').bxSlider({
          mode: 'fade',//horizontal, vertical, fade
          auto: true,
          pause: 2000
      });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %}

<div class="slider">
    <div>
        <img src="{% static 'app/img/banner/banner_1.jpg' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner_2.jpg' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner_3.jpg' %}" alt="">
    </div>
</div>

<tr>
    <td colspan="3">
        <hr>
    </td>
</tr>
<tr width="40%">
&nbsp;
</tr>
<div class="container" align="center">    
    {% csrf_token %}
    <div class="row">            
        <div class="col-md-4">
        </div>
        <div class="col-md-4">                                
            <!-- <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'home' %}">Inicio</a>
            </div> -->
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'contacto' %}">Contacto</a>
            </div>
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'galeria' %}">Galería</a>
            </div>
            
            {% if perms.app.add_producto %}
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'agregar_producto' %}">Nuevo Producto</a>
            </div>
            {% endif %}
            
            {% if perms.app.view_producto %}
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'listar_productos' %}">Listado Producto</a>
            </div>
            {% endif %}
            
            {% if perms.app.add_proveedores %}
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'agregar_proveedores' %}">Nuevo Proveedor</a>
            </div>
            {% endif %}

            {% if perms.app.view_proveedores %}
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'listar_proveedores' %}">Listado Proveedores</a>
            </div>
            {% endif %}

            {% if perms.app.add_clientes %}
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'agregar_cliente' %}">Nuevo Cliente</a>
            </div>
            {% endif %}

            {% if perms.app.view_cliente %}
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'listar_cliente' %}">Listado de Clientes</a>
            </div>            
            {% endif %}
            <div class="col-md-12">
                <a class="btn btn-secondary text-white btn-lg btn-block w-100 mb-3" href="{% url 'listar_contacto' %}">Mostrar Contactos</a>
            </div>                        
        </div>
        <hr>
        {% if user.is_authenticated %}
            
        {% else %}
            
        {% endif %}
        <div class="col-md-4">
        </div>           
    </div>
</div>
{% endblock %}